### ISSUE TITLE
Double variants do not work

### ISSUE THREAD

**Issue by tatue64** [mitsuba-renderer/mitsuba2#18] opened 2020-03-06 15:54 UTC
I managed to compile mitsuba2 with clang all in manjaro linux. The single variants that  I have checked (scalar_rgb, scalar_spectral, scalar_spectral_polarization, packet_rgb, packet_spectral) all work and produce seemingly correct images, but none of the corresponding double variants seems to be correct . 

I checked this with the scenes "matpreview.xml" and "hello.xml" provided in mitsuba-data on git. The "hello.xml" produces endless numbers of warnings of the kind "[ImageBlock] Invalid  sample value: [x, y, -nan, 1, 1]" and I have not waited for the result. With the scene "matpreview.xml", mitsuba segfaults after loading the plugin "perspective.so".

Are these know issues? Could this be related to some incompatible compiler settings (with mitsuba 0.6 compiling with double was not compatible with some processor features)?

**Comment by wjakob** [comment] 2020-03-06 16:11
@tatue64, it's probably a bug on our side. We haven't worked with the double precision variants for a while, and it's quite possible that a bug snuck in. In the next weeks, we want to revive our continuous integration service to catch such per-variant regressions in the future.

**Comment by arpit15** [comment] 2020-03-07 02:32
@tatue64 which variant did you compile with? I tried with `scalar_mono_double` and get compile time errors for `libmitsuba-core.so` . [Here](https://gist.github.com/arpit15/497867bbe8f819f426f289deb89f8f78) is the log from terminal. 

## System configs
Ubuntu 18.04
Clang 9.0.0-2
cmake 3.16.0
ninja 1.8.2
python 3.6.9

**Comment by tatue64** [comment] 2020-03-07 10:53
**@arpit64** I just compiled the variant `scalar_mono_double` without problems after a `git pullall` to include all recent patches. 

The issue I have is that the compiled double variants do not **work** correctly, i.e. crash or at least do not produce a useful output. As Wenzel Jacob stated in his answer, they have not tested these double variants for a long time. Thus, it would probably best  to stick with single_precision variants, which work great so far. (I have not tested the gpu versions, though, because they do not compile with optix 7 but only with optix 6.5)

My configuration (I use a rolling release and thus fairly recent versions of all tools)
- Manjaro Linux with kernel 5.5.8-1 (testing branch)
- clang 9.0.1
-  cmake 3.16.5
- ninja 1.10.0
- python 3.8.1

**Comment by Speierers** [comment] 2020-05-19 09:25
With latest `master` the `scalar_mono_double` now compiled and renders on my machine. This was probably related to some bugs that have been fix since the opening of this issue. Therefore I will close this. Please let us know if this is still an issue on your side.

**Closed by Speierers** 2020-05-19 09:25 UTC
