### ISSUE TITLE
[❔ other question] Ray passing through shape without interaction

### ISSUE THREAD

**Issue by MaximilianBader** [mitsuba-renderer/mitsuba2#502] opened 2021-09-29 14:34 UTC
## Summary

I tracked the interaction points of a ray in the ray-tracing process and figured out that the ray passes through a shape lacking a surface interaction. I don't understand, why this occurs, because from my understanding, the ray should automatically create a surface interaction. The ray is discarded in the simulation, because the weight is 0, but nevertheless I'm bewildered that the ray can pass through without triggering a surface interaction.

## Description

I have a very basic scenario to simulate in mitsuba2 consisting of an area emitter (z=-0.06) and detector (z=0) on opposite sides of a interface (z=0.015). I wanted to simulate the transmission through the interface depending on the indices of reflection assigned to the different sides of the interface. 

Observing the points of surface interactions, I can see that the ray starts at the sensor and is reflected back on the interface at z=-0.015. Then it interacts with the sensor at z=0 again, but is then directly passing through to the emitter at z=-0.06. Geometrically the path of propagation has to pass through the interface. To the best of my knowledge, rays cannot pass through a shape without this surface interaction. So why does this ray then pass through the interface?

Interaction points for the ray: [[-0.0459384, 0.00923075, 0], [-0.0173129, 0.00811458, -0.015], [0.0113125, 0.00699841, 1.28653e-11], [-0.0190324, 0.0382978, -0.06]], 

Visualization:
![scene_ray_visualization_incl_zero_weight_rays](https://user-images.githubusercontent.com/43639142/135286027-216ef57d-cc59-4a06-b0e0-104b565b8718.jpeg)

## Steps to reproduce

I implemented a path tracer which tracks the scene interaction points for all rays. The method is called `sample_with_length_and_origin`. You can find the implementation on Github (starting in line 562): [mitsuba2/PathLengthIntegrator](https://github.com/MaximilianBader/mitsuba2/blob/master/src/librender/integrator.cpp)

Scene file:
```xml
<scene version="2.0.0">
    
    <!-- Define basic path tracer modeling maximum of 7 scattering events -->
    <!-- integrator type="path"-->
	<integrator type="path_ultrasound">
	    <integer name="max_depth" value="7"/>
    </integrator>

	<shape type="rectangle">
    	<transform name="to_world">
      		<scale x="0.05" y="0.05"/>
      		<translate x="0" y="0" z="-0.06" />
    	</transform>
		<emitter type="area">
        	<spectrum name="radiance" value="10.0"/>
    	</emitter>
	</shape>

	<!-- Add membrane of transducer -->
	<shape type="rectangle">
		<transform name="to_world">
			<scale x="0.06" y="0.06" />			<!-- scale x="0.04" y="0.02" /-->
			<translate x="0" y="0" z="-0.015" />
		</transform>
        <bsdf type="dielectric">
			<float name="int_ior" value="0.88"/> <!-- heavy water 0.88 -->
			<float name="ext_ior" value="1"/> <!-- water -->
		</bsdf>
	</shape>

    <!-- Add detector  -->
	<shape type="rectangle">
        <transform name="to_world">
            <scale x="0.05" y="0.05"/>
            <translate x="0" y="0" z="0"/>
        </transform>
        <boolean name="flip_normals" value="true"/>
        <sensor type="irradiancemeter">
            <film type="hdrfilm">
                <integer name="width" value="1"/>
                <integer name="height" value="1"/>
                <string name="pixel_format" value="luminance"/>
                <string name="file_format" value="pfm"/>
                <string name="component_format" value="float32"/>
            </film>
            <sampler type="independent">
                <integer name = "sample_count" value = "1000"/>
            </sampler>
        </sensor>
    </shape>

</scene>
```

Python script:
```python
import os
import numpy as np
import h5py
from pathlib import Path
import matplotlib.pyplot as plt
from scipy.io import savemat
import enoki as ek
import mitsuba

# Set the desired mitsuba variant
mitsuba.set_variant('scalar_mono')

from mitsuba.core import Float, UInt32, UInt64, Vector2f, Vector3f
from mitsuba.core import Bitmap, Struct, Thread
from mitsuba.core.xml import load_file
from mitsuba.render import ImageBlock

# Relative path to the scene XML file, appended to FileResolvers's search path & loaded into mitsuba
filename = r'mitsuba_scenes/us_scene_transmission_through_membrane.xml'
Thread.thread().file_resolver().append(os.path.dirname(filename))
scene = load_file(filename)

# Instead of calling the scene's integrator, we build our own small integrator
# This integrator simply computes the depth values per pixel
integrator = scene.integrator()
sensors = scene.sensors()
emitters = scene.emitters()

# declare list for all interaction points of all rays
interaction_points_all_rays = []
weights_all_rays = []

index_sensor = 0
while index_sensor < len(sensors):

    sensor = sensors[index_sensor]
    film = sensor.film()
    sampler = sensor.sampler()
    film_size = film.crop_size()
    spp = 100000

    # Seed the sampler
    total_sample_count = ek.hprod(film_size) * spp
    diff_scale_factor = ek.rsqrt(sampler.sample_count())

    if sampler.wavefront_size() != total_sample_count:
        sampler.seed(0, total_sample_count)

    pos = Vector2f(0,0)
    scale = Vector2f(1.0 / film_size[0], 1.0 / film_size[1])

    num_hitting_rays = 0
    num_hitting_rays_zero_weight = 0
    total_weight_rays = 0

    index_ray = 0
    while index_ray < total_sample_count:
        pos += sampler.next_2d()

        # Sample single ray starting from the ultrasound transducer
        ray, weight = sensor.sample_ray_differential(
            time=0,
            sample1=sampler.next_1d(),
            sample2=pos * scale,
            sample3=sampler.next_2d()
        )
        ray.scale_differential(diff_scale_factor)
        
        (spectrum, interaction_points_per_ray, active) = integrator.sample_with_length_and_origin(scene,sampler,ray,active=True)
        if active:
            for index_list in range(0,len(interaction_points_per_ray)):
                weight_per_sensor[index_sensor] += spectrum[index_list]
                num_hitting_rays_per_sensor[index_sensor] += 1
                interaction_points_all_rays.append(interaction_points_per_ray[index_list])
                weights_all_rays.append(spectrum[index_list])

        sampler.advance()
        index_ray += 1

    index_sensor += 1
```

**Comment by Speierers** [comment] 2021-09-30 06:41
Hi @MaximilianBader,

Two things I would suggest you try:
1. Run this simulation with a double precision variant
2. Scale up your scene uniformly to see whether this issue is still happening.

Be aware that `ray = si.spawn_ray(si.to_world(bs.wo));` will slightly offset the ray origin (`mint > 0`) to avoid re-intersection the surface we are leaving. Maybe this offset is too strong in your application?

**Comment by MaximilianBader** [comment] 2021-09-30 08:27
Hi @Speierers ,

I both ran the simulation with double precision and scaled up the scene uniformly. The ray still passes through the interface without creating a surface interaction.

Regarding the offset of the newly spawned ray: This should not be an issue for a scaled up scene, right? I scaled up the scene by a factor of 100 and in this case, the offset of the ray origin would have to be `> 1.5m`.

**Comment by MaximilianBader** [comment] 2021-10-01 06:14
Hi @Speierers,

I further investigated the issue and could find out the following:
Actually, there is no additional ray sampled for the last surface interaction at point  [0.0113125, 0.00699841, 1.28653e-11]. Instead the emitter is sampled in that direction (refer to [path tracer - sample()](https://github.com/mitsuba-renderer/mitsuba2/blob/master/src/integrators/path.cpp#L158)) and `emitter_val=[0]` is returned. For me it seems like the emitter sampling (`scene->sample_emitter_direction(si, sampler->next_2d(active_e), true, active_e)`) does not consider the necessary intersection of the ray with the interface, but rather `emitter_val` is set to 0 due to the shadowing by the interface. Does this sound reasonable for you?

**Comment by Speierers** [comment] 2021-10-01 06:20
Yes that sound reasonable. You should be able to turn off the shadow test in `sample_emitter_direction` by passing `false` as 3rd argument. Then you can handle this properly on the integrator side.

**Comment by MaximilianBader** [comment] 2021-10-01 06:33
@Speierers thanks for the suggestion. I did turn off the visibility test and then indeed the `weight > 0` was returned. But how do you suggest to handle this properly on the integrator side? Isn't it physically reasonable that no ray can pass through the interface without causing an interaction?

**Comment by Speierers** [comment] 2021-10-01 14:56
Yes. During the first bounce the connection to the emitter should fail because of the occlusion caused by this surface. Then the second bounce in your integrator will handle those connection properly, this time without any occlusion.

I am closing this as it isn't an issue with the library itself 😉

**Closed by Speierers** 2021-10-01 14:56 UTC
