### ISSUE TITLE
[🔨 compilation issue] packet polarised variants problem

### ISSUE THREAD

**Issue by Vutshi** [mitsuba-renderer/mitsuba2#494] opened 2021-09-08 12:24 UTC
## Summary

Hi, I have problem building packet polarised variants of Mitsuba 2 master.

## System configuration

- Platform: macOS, Ubuntu
- Compiler: clang-12, gcc-10
- Python version: 3.8
- Mitsuba 2 version: master

## Description

Compiling `packet_rgb_polarized` variant generates the following errors with clang-12 on macOS:

```
include/mitsuba/core/traits.h:67:82: error: no type named 'Scalar' in 'mitsuba::detail::spectrum_traits<enoki::Array<enoki::Array<mitsuba::Color<enoki::Packet<float, 16>, 3>, 4>, 4>>'
    using Scalar       = enoki::detail::MaskedArray<typename spectrum_traits<T>::Scalar>;
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
include/mitsuba/core/traits.h:68:82: error: no type named 'Wavelength' in 'mitsuba::detail::spectrum_traits<enoki::Array<enoki::Array<mitsuba::Color<enoki::Packet<float, 16>, 3>, 4>, 4>>'
    using Wavelength   = enoki::detail::MaskedArray<typename spectrum_traits<T>::Wavelength>;
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
/Users/x2241064/Install/3D/Mitsuba_2/mitsuba2-current/include/mitsuba/core/traits.h:69:82: error: no type named 'Unpolarized' in 'mitsuba::detail::spectrum_traits<enoki::Array<enoki::Array<mitsuba::Color<enoki::Packet<float, 16>, 3>, 4>, 4>>'
    using Unpolarized  = enoki::detail::MaskedArray<typename spectrum_traits<T>::Unpolarized>;
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
1 warning and 3 errors generated.
```
Variant `packet_spectral_polarized` does not work either. Same problem I see on Ubuntu with gcc-10.

## Steps to reproduce

Compile with the following configuration
[mitsuba.conf.txt](https://github.com/mitsuba-renderer/mitsuba2/files/7128783/mitsuba.conf.txt)

**Comment by tizian** [comment] 2021-09-08 16:14
Duplicate of #467.
The work on the next release of Mitsuba 2 (#490) is still ongoing---as of yet, only the scalar variants with polarization are expected to compile correctly.

**Closed by tizian** 2021-09-08 16:14 UTC
