### ISSUE TITLE
Extra energy in some buckets - diffuse sphere under area lights

### ISSUE THREAD

**Issue by eugenedeon** [mitsuba-renderer/mitsuba2#96] opened 2020-04-20 22:31 UTC
I notice bucket-based energy creation for both MacOS and Win10 builds of yesterdays master when using the attached xml file, and variants thereof where integrator is varied to volpath and volpathmis.

[scenes2.0.zip](https://github.com/mitsuba-renderer/mitsuba2/files/4506589/scenes2.0.zip)

Mitsuba version 2.0.0 (master[a168f29a], Windows, 64bit, 20 threads, 8-wide SIMD)
2020-04-21 10:23:37 INFO  main  [mitsuba.cpp:195] Copyright 2019, Realistic Graphics Lab, EPFL
2020-04-21 10:23:37 INFO  main  [mitsuba.cpp:196] Enabled processor features: avx2 avx fma f16c sse4.2 x86_64
2020-04-21 10:23:37 INFO  main  [xml.cpp:1146] Loading XML file "..\..\scenes2.0\fog_bench_2path.xml" ..
2020-04-21 10:23:37 INFO  main  [xml.cpp:1147] Using variant "scalar_rgb"

**Comment by dvicini** [comment] 2020-04-21 12:50
Hi Eugene, 
Thanks for reporting this. I was able to reproduce your problem even with the regular path tracer. It turned out the issue was related to the rectangle shape's sampling method not initializing all fields of the returned DirectionSample record. I pushed a fix.
Delio

**Closed by dvicini** 2020-04-21 12:50 UTC

**Comment by wjakob** [comment] 2020-04-21 12:55
Awesome, thanks Delio!

**Comment by eugenedeon** [comment] 2020-04-21 22:15
Thanks!  In the attached fog_bench_2.xml above, the atmosphere does not appear in the render (with volpath or volpathmis).  Are cameras beginning in the medium supported currently?

**Comment by dvicini** [comment] 2020-04-22 12:21
You are right, this was missing. I pushed a fix. It's not super well tested, but it seems to work. Btw. I would recommend using `volpathmis` to render this scene, since the `volpath` integrator does not do MIS inside the medium. Also we currently only support albedo/sigma_t parameters and not sigma_a/sigma_s. So you have to convert your parameters first. The reason we do that is that with the whole spectral rendering machinery, converting these parameters internally is a bit more involved than in Mitsuba 1, so for now we avoid it and just expect the user to provide albedo/sigmat.

I also just found a bug that environment emitters won't render properly with a medium filling the full scene. I will fix it eventually, but this is a bit more involved.

**Comment by eugenedeon** [comment] 2020-04-22 21:02
Thanks.  (mfp,albedo) would be ideal for homogeneous media in anticipation of supporting non-exponential random media.

**Comment by eugenedeon** [comment] 2020-04-22 22:13
Thanks for the fix, I can confirm it matches 0.6 and PBRTv3.

**Comment by dvicini** [comment] 2020-04-23 07:29
Nice! Thanks for checking against PBRT and 0.6, it's been a while since I did that.
