### ISSUE TITLE
Very long rendering time using volpath-simple plugin

### ISSUE THREAD

**Issue by schunkes** [mitsuba-renderer/mitsuba2#76] opened 2020-04-10 11:58 UTC
# Issue description
The `volpath-simple` integrator renders very slowly when used with scenes as follows:
- Geometry and optical properties: a cube (`obj` plugin) filled with a homogeneous medium (isotropic phase function); the cube is intersected by a rectangle that holds a `diffuse` bsdf and extends beyond the boundaries of the cube. 
- Illumination: a `constant` emitter.
- Sensor: a `perspective` camera.

Rendering this scene with the `scalar_mono` variant with unlimited path length yields a rendering time of around one hour on a recent MacMini,
while limiting the maximum path length to values as high as 200000 reduces the rendering time to less than a few seconds.
The scene and obj files are attached.

# Steps to reproduce
Set the maximum path length parameter `max_depth` in the XML file to -1 for unlimited path length and render the scene in `scalar_mono` mode.

The scene expects the obj file to be named `cube.obj` and be placed alongside it.

# Setup used to build and run Mitsuba
- OS: macOS 10.15.4
- Compiler: Clang 11.XX

# Further observations
- The problem does not occur, when the `volpath` integrator is used instead of the `volpath-simple` integrator.
- Reducing the film size and samples per pixel sometimes leads to this problem not occurring however we were not able to find consistent limits for these values.
- The problem occurs if the rectangle is removed and only cube is present in the scene.
- The problem does not occur if the scene contains only an analytical sphere filled with the same homogeneous medium.
- The problem does not occur for the obj cube without an internal medium

The geometrical variants can be created from the same scene file by commenting the respective parts.

# Scene XML file
``` xml
<scene version="2.0.0">
    <integrator type="volpathsimple">
        <integer name="max_depth" value="4096"/>
    </integrator>
    <sensor type="perspective">
        <transform name="to_world">
            <lookat origin="0, -4, 3" target="0, 0, 0" up="0, 0, 1"/>
        </transform>
        <film type="hdrfilm">
            <integer name="width" value="256"/>
            <integer name="height" value="256"/>
            <string name="pixel_format" value="luminance"/>
        </film>
        <sampler type="independent">
            <integer name="sample_count" value="64"/>
        </sampler>
    </sensor>
    <emitter type="constant"/>
    <medium type="homogeneous" id="participating_medium">
        <float name="density" value="1"/>
        <spectrum name="sigma_t" value="1"/>
        <spectrum name="albedo" value="0"/>
        <phase type="isotropic"/>
    </medium>
    <!-- <shape type="sphere">
        <point name="center" value="0.0, 0.0, 0.0"/>
        <float name="radius" value="2.0"/>
        <bsdf type="null"/>
        <ref id="participating_medium" name="interior"/>
    </shape> -->
    <shape type="obj">
        <string name="filename" value="cube.obj"/>
        <bsdf type="null"/>
        <ref id="participating_medium" name="interior"/>
    </shape>
    <shape type="rectangle">
        <bsdf type="diffuse">
            <spectrum name="reflectance" value="0.5"/>
        </bsdf>
    </shape>
</scene>
```

# Cube obj file
``` none
o Cube.002_Cube.005
v -0.500000 -0.500000 0.500000
v -0.500000 0.500000 0.500000
v -0.500000 -0.500000 -0.500000
v -0.500000 0.500000 -0.500000
v 0.500000 -0.500000 0.500000
v 0.500000 0.500000 0.500000
v 0.500000 -0.500000 -0.500000
v 0.500000 0.500000 -0.500000
vt 0.625000 0.000000
vt 0.375000 0.250000
vt 0.375000 0.000000
vt 0.625000 0.250000
vt 0.375000 0.500000
vt 0.625000 0.500000
vt 0.375000 0.750000
vt 0.625000 0.750000
vt 0.375000 1.000000
vt 0.125000 0.750000
vt 0.125000 0.500000
vt 0.875000 0.500000
vt 0.625000 1.000000
vt 0.875000 0.750000
vn -1.0000 0.0000 0.0000
vn 0.0000 0.0000 -1.0000
vn 1.0000 0.0000 0.0000
vn 0.0000 0.0000 1.0000
vn 0.0000 -1.0000 0.0000
vn 0.0000 1.0000 0.0000
s off
f 2/1/1 3/2/1 1/3/1
f 4/4/2 7/5/2 3/2/2
f 8/6/3 5/7/3 7/5/3
f 6/8/4 1/9/4 5/7/4
f 7/5/5 1/10/5 3/11/5
f 4/12/6 6/8/6 8/6/6
f 2/1/1 4/4/1 3/2/1
f 4/4/2 8/6/2 7/5/2
f 8/6/3 6/8/3 5/7/3
f 6/8/4 2/13/4 1/9/4
f 7/5/5 5/7/5 1/10/5
f 4/12/6 2/14/6 6/8/6
```

**Comment by dvicini** [comment] 2020-04-10 12:06
Hi Sebastian,
Thanks for the detailed error report. I think the problem is most likely that I accidentally left the Russian roulette commented out in the volumetric path tracer. I will push a fix shortly
Delio

**Comment by dvicini** [comment] 2020-04-10 18:56
I pushed a fix and also fixed a few issues in the full volpath. There are still a few things on my todo list for the volume implementation, so just let me know if you run into any issues and then I can prioritize them 
Delio

**Closed by dvicini** 2020-04-10 18:56 UTC
